#ifndef __DEVICE_DENON_H__
#define __DEVICE_DENON_H__

#define DENON_POWER_TOGGLE      "DENON_POWER_TOGGLE"
#define DENON_VOL_MINUS         "DENON_VOL_MINUS"
#define DENON_VOL_PLUS          "DENON_VOL_PLUS"
#define DENON_VOL_MUTE          "DENON_VOL_MUTE"
#define DENON_CHAN_PLUS         "DENON_CHAN_PLUS"
#define DENON_CHAN_MINUS        "DENON_CHAN_MINUS"
#define DENON_INPUT_CABLESAT    "DENON_INPUT_CABLESAT"
#define DENON_INPUT_MEDIAPLAYER "DENON_INPUT_MEDIAPLAYER"
#define DENON_INPUT_BLURAY      "DENON_INPUT_BLURAY"
#define DENON_INPUT_GAME        "DENON_INPUT_GAME"
#define DENON_INPUT_AUX1        "DENON_INPUT_AUX1"
#define DENON_INPUT_AUX2        "DENON_INPUT_AUX2"
#define DENON_INPUT_TV          "DENON_INPUT_TV"
#define DENON_INPUT_BLUETOOTH   "DENON_INPUT_BLUETOOTH"
#define DENON_INPUT_HEOS        "DENON_INPUT_HEOS"
#define DENON_INFO              "DENON_INFO"
#define DENON_OPTION            "DENON_OPTION"
#define DENON_BACK              "DENON_BACK"
#define DENON_SETUP             "DENON_SETUP"
#define DENON_MENU_ENTER        "DENON_MENU_ENTER"
#define DENON_MENU_UP           "DENON_MENU_UP"
#define DENON_MENU_LEFT         "DENON_MENU_LEFT"
#define DENON_MENU_RIGHT        "DENON_MENU_RIGHT"
#define DENON_MENU_DOWN         "DENON_MENU_DOWN"
#define DENON_SOUNDMODE_MOVIE   "DENON_SOUNDMODE_MOVIE"
#define DENON_SOUNDMODE_MUSIC   "DENON_SOUNDMODE_MUSIC"
#define DENON_MEDIA_PREV        "DENON_MEDIA_PREV"
#define DENON_MEDIA_PLAYPAUSE   "DENON_MEDIA_PLAYPAUSE"
#define DENON_MEDIA_NEXT        "DENON_MEDIA_NEXT"

void register_device_denon();

#endif /*__DEVICE_DENON_H__*/
