#ifndef __DEVICE_SMARTHOME_H__
#define __DEVICE_SMARTHOME_H__

#define SMARTHOME_MQTT_AIRCON_SETMODE        "SMARTHOME_MQTT_AIRCON_SETMODE"
#define SMARTHOME_MQTT_AIRCON_SETFAN         "SMARTHOME_MQTT_AIRCON_SETFAN"
#define SMARTHOME_MQTT_VRPC_WAKE             "SMARTHOME_MQTT_VRPC_WAKE"
#define SMARTHOME_MQTT_TV_POWEROFF           "SMARTHOME_MQTT_TV_POWEROFF"
#define SMARTHOME_MQTT_TV_POWERON            "SMARTHOME_MQTT_TV_POWERON"
#define SMARTHOME_MQTT_XBOX_POWERON          "SMARTHOME_MQTT_XBOX_POWERON"
#define SMARTHOME_MQTT_VRSENSORS_POWER       "SMARTHOME_MQTT_VRSENSORS_POWER"
#define SMARTHOME_MQTT_BLINDSCOUCH_TOGGLE    "SMARTHOME_MQTT_BLINDSCOUCH_TOGGLE"
#define SMARTHOME_MQTT_BLINDSWINDOW_SETPOS   "SMARTHOME_MQTT_BLINDSWINDOW_SETPOS"

#define SMARTHOME_MQTT_BULB1_SET                   "Smarthome_mqtt_bulb1_set"
#define SMARTHOME_MQTT_BULB2_SET                   "Smarthome_mqtt_bulb2_set"
#define SMARTHOME_MQTT_BULB1_BRIGHTNESS_SET        "Smarthome_mqtt_bulb1_brightness_set"
#define SMARTHOME_MQTT_BULB2_BRIGHTNESS_SET        "Smarthome_mqtt_bulb2_brightness_set"

void register_device_smarthome();

#endif /*__DEVICE_SMARTHOME_H__*/
